// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsMeter.Infrastructure.Data;

#nullable disable

namespace NewsMeter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("NewsMeter.Core.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationChannelIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhraseId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.HasIndex("PhraseId", "PubDate");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.GlobalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultMinAbsolute")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefaultMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultNotificationChannelIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FetchIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyPhrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinAbsolute")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Multiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.RssSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RssSources");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.SpikeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelsNotified")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RollingAverage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("PhraseId", "Date");

                    b.ToTable("SpikeEvents");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.AlertRule", b =>
                {
                    b.HasOne("NewsMeter.Core.Entities.Phrase", "Phrase")
                        .WithMany("AlertRules")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.Article", b =>
                {
                    b.HasOne("NewsMeter.Core.Entities.Phrase", "Phrase")
                        .WithMany("Articles")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.RssSource", b =>
                {
                    b.OwnsOne("NewsMeter.Core.Entities.RssFieldMapping", "FieldMapping", b1 =>
                        {
                            b1.Property<Guid>("RssSourceId");

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<string>("Guid")
                                .IsRequired();

                            b1.Property<string>("Link")
                                .IsRequired();

                            b1.Property<string>("PubDate")
                                .IsRequired();

                            b1.Property<string>("PubDateFormat")
                                .IsRequired();

                            b1.Property<string>("Source")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1.HasKey("RssSourceId");

                            b1.ToTable("RssSources");

                            b1
                                .ToJson("FieldMapping")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("RssSourceId");
                        });

                    b.Navigation("FieldMapping")
                        .IsRequired();
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.SpikeEvent", b =>
                {
                    b.HasOne("NewsMeter.Core.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsMeter.Core.Entities.Phrase", "Phrase")
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("NewsMeter.Core.Entities.Phrase", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
